# -*- coding: utf-8 -*-
"""regressao_linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmYOR-EDo6yVm3qZY4VmnmtPsLQi2s7D
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

path_to_data_set = '/content/drive/MyDrive/Colab Notebooks/candidatos.csv'

data_frame = pd.read_csv(path_to_data_set)

import math
avg_test_score = math.floor(data_frame['test_score'].median())
data_frame['test_score'] = data_frame['test_score'].fillna(avg_test_score)

!pip install word2number

from word2number import w2n
for index in range(len(data_frame['experience'])):
  if not (str(data_frame['experience'][index]) == 'nan'):
    data_frame['experience'][index] = w2n.word_to_num(str(data_frame['experience'][index]))

avg_experience = math.floor(data_frame['experience'].median())
data_frame['experience'] = data_frame['experience'].fillna(avg_experience)

reg = linear_model.LinearRegression()
reg.fit(data_frame[['experience', 'test_score', 'interview_score']], data_frame['salary'])

jr = [[1, 5, 6]]
reg.predict(jr)

pl = [[6, 7, 8]]
reg.predict(pl)